import type { Metadata } from "next";

import "./globals.css";

import Pagee from './pagee'





export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout() {
  return (
    <html lang="en">
      <body>
        <Pagee />
      </body>
    </html>
  );
}
